import Link from "next/link";
import { ArrowRight, CheckCircle2, MessageCircleHeart, Sparkles, UsersRound } from "lucide-react";

export default function Home() {
  return <main className="min-h-screen overflow-hidden bg-[#fbf9f8] px-5 py-5 sm:px-8 lg:px-12">
    <header className="mx-auto flex max-w-[1320px] items-center justify-between py-3"><Link className="dh-heading text-3xl font-bold sm:text-4xl" href="/">DietHub</Link><Link href="/giris" className="dh-focus rounded-xl border border-[#163827] px-4 py-2 text-sm font-semibold text-[#163827] hover:bg-[#e8f2ec]">Demo girişi</Link></header>
    <section className="mx-auto grid min-h-[calc(100vh-108px)] max-w-[1320px] items-center gap-12 py-12 lg:grid-cols-[1.05fr_.95fr] lg:py-16">
      <div className="max-w-2xl"><span className="inline-flex items-center gap-2 rounded-full bg-[#e8f2ec] px-3 py-1.5 text-sm font-semibold text-[#2d4f3d]"><Sparkles size={16} />Diyetisyenler için profesyonel alan</span><h1 className="dh-heading mt-6 text-5xl font-bold leading-[1.02] sm:text-6xl lg:text-7xl">Beslenme takibini <span className="text-[#315c48]">tek ve sakin</span> bir deneyimde yönetin.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-[#5e625d]">Danışanlarınızı, programlarınızı, kamplarınızı ve iletişimi DietHub&apos;ın demo deneyiminde bir arada görün.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/giris/diyetisyen" className="dh-focus inline-flex items-center justify-center gap-2 rounded-xl bg-[#2d4f3d] px-6 py-3.5 font-semibold text-white hover:bg-[#163827]">Diyetisyen olarak devam et <ArrowRight size={19} /></Link><Link href="/giris/danisan" className="dh-focus inline-flex items-center justify-center rounded-xl bg-[#e7e2d8] px-6 py-3.5 font-semibold text-[#163827] hover:bg-[#ddd6c9]">Danışan olarak devam et</Link></div><p className="mt-4 text-sm text-[#747771]">Bu alan yalnızca örnek verilerle çalışan bir frontend demosudur.</p></div>
      <div className="relative mx-auto w-full max-w-[520px]"><div className="absolute -right-10 top-12 h-44 w-44 rounded-full bg-[#e8f2ec]" /><div className="absolute -bottom-10 -left-8 h-32 w-32 rounded-full bg-[#e7e2d8]" /><div className="dh-card relative overflow-hidden p-5 sm:p-7"><div className="rounded-[20px] bg-[#2d4f3d] p-6 text-white"><p className="text-xs font-bold uppercase tracking-[.12em] text-[#c5ecd3]">Bugünün özeti</p><h2 className="mt-3 font-[family-name:var(--font-heading)] text-3xl font-bold">Her adım yerli yerinde.</h2><div className="mt-7 h-2 overflow-hidden rounded-full bg-white/20"><div className="h-full w-[72%] rounded-full bg-[#c5ecd3]" /></div><div className="mt-2 flex justify-between text-sm text-white/80"><span>Günlük ilerleme</span><span>%72</span></div></div><div className="mt-5 grid grid-cols-2 gap-4"><Metric icon={<UsersRound size={21} />} label="Aktif danışan" value="48" /><Metric icon={<CheckCircle2 size={21} />} label="Bekleyen check-in" value="7" /></div><div className="mt-5 rounded-2xl border border-[#ebe8e2] p-4"><div className="flex items-center gap-3"><span className="rounded-full bg-[#e8f2ec] p-2 text-[#2d4f3d]"><MessageCircleHeart size={20} /></span><div><p className="font-semibold">Ayşe&apos;den yeni mesaj</p><p className="mt-0.5 text-sm text-[#6c706a]">Programı tamamladığını paylaştı.</p></div></div></div></div></div>
    </section>
  </main>;
}

function Metric({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <div className="rounded-2xl bg-[#f7f5f0] p-4"><span className="text-[#2d4f3d]">{icon}</span><p className="dh-heading mt-3 text-2xl font-bold">{value}</p><p className="mt-0.5 text-sm text-[#656761]">{label}</p></div>; }
