"use client";
import { useState } from "react";
import { Check, Leaf, Plus, Save, Sun, Utensils } from "lucide-react";

export function CampForm() {
  const [saved, setSaved] = useState(false); const [day, setDay] = useState(1);
  return <form onSubmit={(event) => { event.preventDefault(); setSaved(true); }} className="dh-card p-6 sm:p-9"><div className="flex flex-col gap-4 border-b border-[#e2dfd9] pb-7 sm:flex-row sm:items-center sm:justify-between"><h2 className="dh-heading flex items-center gap-3 text-2xl font-bold"><Leaf size={26} />Kamp Detayları</h2><div className="flex gap-3"><button type="button" onClick={() => setSaved(true)} className="dh-focus inline-flex items-center gap-2 rounded-xl border border-[#163827] px-4 py-3 font-semibold text-[#163827]"><Save size={18} />Taslak Kaydet</button><button type="submit" className="dh-focus inline-flex items-center gap-2 rounded-xl bg-[#2d4f3d] px-4 py-3 font-semibold text-white"><Check size={18} />Kampı Yayınla</button></div></div>{saved && <p className="mt-5 rounded-xl bg-[#e8f2ec] px-4 py-3 text-sm font-medium text-[#2d4f3d]">Demo kamp bilgileri kaydedildi.</p>}<div className="mt-8 grid gap-6 lg:grid-cols-2"><label className="text-sm font-semibold">Kamp Adı<input required className="dh-input mt-2" defaultValue="21 Günlük Dengeli Yaşam Kampı" /></label><label className="text-sm font-semibold">Kamp Açıklaması<textarea className="dh-textarea mt-2" defaultValue="Danışanların günlük küçük adımlarla düzenli beslenme rutinleri oluşturmasına eşlik eden örnek kamp." /></label><label className="text-sm font-semibold">Başlangıç Tarihi<input className="dh-input mt-2" type="date" defaultValue="2024-05-13" /></label><label className="text-sm font-semibold">Süre (gün)<input className="dh-input mt-2" type="number" defaultValue="21" min="1" /></label></div><div className="mt-9 border-t border-[#e2dfd9] pt-8"><h2 className="dh-heading text-2xl font-bold">Günlük Program Kurgusu</h2><div className="mt-5 flex gap-2 overflow-x-auto pb-2">{[1,2,3,4,5].map((item) => <button type="button" key={item} onClick={() => setDay(item)} className={`dh-focus shrink-0 rounded-full px-6 py-3 font-semibold ${day === item ? "bg-[#2d4f3d] text-white" : "bg-[#f0eeea] text-[#333631]"}`}>{item}. Gün</button>)}<button type="button" className="dh-focus rounded-full bg-[#f0eeea] p-3 text-[#163827]" aria-label="Yeni gün ekle"><Plus size={20} /></button></div><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-4"><MealSetup icon={<Sun size={23} />} title="Kahvaltı" note="Güne limonlu su ile başla" /><MealSetup icon={<Utensils size={23} />} title="Ara Öğün" content="Yeşil Çay & Çiğ Badem" /><MealSetup icon={<Utensils size={23} />} title="Öğle" note="Bol yeşillik tercih et" /><MealSetup icon={<Sun size={23} />} title="Akşam" note="En geç 19:30'da" /></div></div></form>;
}
function MealSetup({ icon, title, note, content }: { icon: React.ReactNode; title: string; note?: string; content?: string }) { return <div className="rounded-2xl border border-[#dedbd4] p-5"><p className="flex items-center gap-3 font-semibold uppercase tracking-[.08em] text-[#163827]">{icon}{title}</p>{content ? <div className="mt-6 rounded-xl border border-[#dfddd7] bg-white p-3"><p className="font-semibold">{content}</p><p className="mt-1 text-sm text-[#696c66]">Porsiyon: 1 fincan / 10 adet</p></div> : <button type="button" className="dh-focus mt-6 flex w-full flex-col items-center rounded-xl border-2 border-dashed border-[#c7cec6] px-3 py-5 text-sm text-[#555954]"><Plus size={22} />Tarif Ekle</button>}<label className="mt-5 block text-xs font-bold uppercase tracking-[.08em] text-[#656861]">Diyetisyen Notu<input className="dh-input mt-2 text-sm" defaultValue={note} placeholder="Not ekleyin" /></label></div>; }
