import Link from "next/link";
import { ArrowRight, CheckCircle2, LockKeyhole } from "lucide-react";

export function LoginScreen({ role }: { role: "diyetisyen" | "danisan" }) {
  const isDietitian = role === "diyetisyen";
  const target = isDietitian ? "/diyetisyen" : "/danisan";
  const title = isDietitian ? "Profesyonel alanınıza hoş geldiniz." : "Kişisel alanınıza hoş geldiniz.";
  return <main className="grid min-h-screen bg-[#fbf9f8] lg:grid-cols-2"><section className="flex flex-col justify-between bg-[#2d4f3d] p-7 text-white sm:p-12"><Link href="/" className="dh-focus font-[family-name:var(--font-heading)] text-4xl font-bold">DietHub</Link><div className="max-w-md py-14"><span className="inline-flex rounded-full bg-white/10 px-3 py-1.5 text-sm font-semibold">Demo deneyimi</span><h1 className="mt-6 font-[family-name:var(--font-heading)] text-4xl font-bold leading-tight sm:text-5xl">{isDietitian ? "İyi takip, güçlü danışan ilişkileriyle başlar." : "Kendi ritminizde, daha düzenli günler."}</h1><div className="mt-10 space-y-4 text-white/85"><Feature text="Örnek verilerle keşfedebileceğiniz çalışan arayüz" /><Feature text="Program, tarif, mesaj ve check-in akışları" /><Feature text="Gerçek hesap ve sağlık verisi içermez" /></div></div><p className="text-sm text-white/65">DietHub frontend ürün demosu</p></section><section className="mx-auto flex w-full max-w-xl items-center px-5 py-12 sm:px-10"><div className="w-full"><Link href="/" className="dh-focus text-sm font-semibold text-[#2d4f3d]">← Ana sayfaya dön</Link><p className="mt-12 text-sm font-bold uppercase tracking-[.12em] text-[#73766f]">{isDietitian ? "Diyetisyen girişi" : "Danışan girişi"}</p><h2 className="dh-heading mt-3 text-4xl font-bold">{title}</h2><p className="mt-3 text-[#666963]">Bu demo için bilgilerinizi girmeniz gerekmiyor. İsterseniz alanları deneyip doğrudan devam edebilirsiniz.</p><form className="mt-8 space-y-5" action={target}><label className="block text-sm font-semibold">E-posta adresi<input className="dh-input mt-2" type="email" placeholder="ornek@diethub.com" /></label><label className="block text-sm font-semibold">Şifre<div className="relative mt-2"><input className="dh-input pr-12" type="password" placeholder="••••••••" /><LockKeyhole className="absolute right-4 top-3.5 text-[#757770]" size={19} /></div></label><button className="dh-focus flex w-full items-center justify-center gap-2 rounded-xl bg-[#2d4f3d] px-5 py-3.5 font-semibold text-white hover:bg-[#163827]" type="submit">Demo olarak devam et <ArrowRight size={19} /></button></form><p className="mt-6 text-center text-sm text-[#6e716b]">Bu demo ekranında gerçek kimlik doğrulama yapılmaz.</p></div></section></main>;
}
function Feature({ text }: { text: string }) { return <p className="flex gap-3"><CheckCircle2 className="mt-0.5 shrink-0 text-[#c5ecd3]" size={20} />{text}</p>; }
