"use client";
import { useState } from "react";
import { Search, Send } from "lucide-react";
import { conversations } from "@/data/demo";
import { Avatar } from "./ui";

type ChatMessage = { text: string; mine: boolean; time: string };
const initialMessages: ChatMessage[] = [
  { text: "Merhaba Ayşe, bugün programın nasıl gidiyor?", mine: true, time: "10:12" },
  { text: "Merhaba hocam, kahvaltımı yaptım. Kendimi oldukça iyi hissediyorum.", mine: false, time: "10:18" },
  { text: "Harika! Öğleden sonra su hedefini de kontrol etmeyi unutma.", mine: true, time: "10:22" },
];
export function MessageConsole({ clientView = false }: { clientView?: boolean }) {
  const [selected, setSelected] = useState(conversations[0]); const [messages, setMessages] = useState(initialMessages); const [draft, setDraft] = useState("");
  const send = () => { if (!draft.trim()) return; setMessages((items) => [...items, { text: draft.trim(), mine: clientView, time: "Şimdi" }]); setDraft(""); };
  return <div className="dh-card grid min-h-[590px] overflow-hidden lg:grid-cols-[310px_minmax(0,1fr)]"><aside className="border-b border-[#e4e2dc] bg-[#fcfbf9] p-4 lg:border-b-0 lg:border-r"><label className="relative block"><span className="sr-only">Konuşma ara</span><Search size={18} className="absolute left-3 top-3 text-[#777970]" /><input className="dh-input py-2.5 pl-10 text-sm" placeholder="Konuşma ara..." /></label><div className="mt-4 space-y-1">{conversations.map((conversation) => <button key={conversation.id} onClick={() => { setSelected(conversation); setMessages(initialMessages); }} className={`dh-focus flex w-full items-center gap-3 rounded-xl p-3 text-left ${selected.id === conversation.id ? "bg-[#e8f2ec]" : "hover:bg-[#f0eeea]"}`}><Avatar initials={conversation.initials} tone={conversation.tone} size="sm" /><div className="min-w-0 flex-1"><div className="flex justify-between gap-2"><p className="truncate font-semibold">{conversation.name}</p><span className="text-xs text-[#787a74]">{conversation.time}</span></div><p className="mt-0.5 truncate text-sm text-[#6c6f69]">{conversation.preview}</p></div>{conversation.unread > 0 && <span className="rounded-full bg-[#2d4f3d] px-2 py-0.5 text-xs font-bold text-white">{conversation.unread}</span>}</button>)}</div></aside><section className="flex min-h-[430px] flex-col"><header className="flex items-center gap-3 border-b border-[#e4e2dc] p-5"><Avatar initials={selected.initials} tone={selected.tone} size="sm" /><div><h2 className="font-semibold">{clientView ? "Diyetisyen Elif Nur" : selected.name}</h2><p className="text-sm text-[#6b6e68]">Çevrimiçi</p></div></header><div className="dh-scrollbar flex flex-1 flex-col gap-4 overflow-y-auto p-5">{messages.map((message, index) => <div key={`${message.text}-${index}`} className={`flex ${message.mine ? "justify-end" : "justify-start"}`}><div className={`max-w-[85%] rounded-2xl px-4 py-3 ${message.mine ? "rounded-br-sm bg-[#2d4f3d] text-white" : "rounded-bl-sm bg-[#f0eeea] text-[#242724]"}`}><p>{message.text}</p><p className={`mt-1 text-right text-[11px] ${message.mine ? "text-white/70" : "text-[#777970]"}`}>{message.time}</p></div></div>)}</div><form onSubmit={(event) => { event.preventDefault(); send(); }} className="flex gap-3 border-t border-[#e4e2dc] p-4"><label className="sr-only" htmlFor="message-text">Mesajınız</label><input id="message-text" value={draft} onChange={(event) => setDraft(event.target.value)} className="dh-input py-3" placeholder="Mesaj yaz..." /><button className="dh-focus rounded-xl bg-[#2d4f3d] px-4 text-white hover:bg-[#163827]" type="submit" aria-label="Mesaj gönder"><Send size={19} /></button></form></section></div>;
}
