import type { ReactNode } from "react";
import { ArrowRight, Inbox } from "lucide-react";

export function Card({ children, className = "" }: { children: ReactNode; className?: string }) { return <section className={`dh-card ${className}`}>{children}</section>; }

const avatarTones = { green: "bg-[#c5ecd3] text-[#163827]", beige: "bg-[#e7e2d8] text-[#615e57]", pink: "bg-[#f9d7d3] text-[#8d4136]", blue: "bg-[#dce9ed] text-[#315765]" };
export function Avatar({ initials, tone = "green", size = "md" }: { initials: string; tone?: keyof typeof avatarTones; size?: "sm" | "md" | "lg" }) { const sizeClass = size === "sm" ? "h-9 w-9 text-xs" : size === "lg" ? "h-16 w-16 text-lg" : "h-12 w-12 text-sm"; return <span aria-label={initials} className={`inline-flex shrink-0 items-center justify-center rounded-full font-semibold ${sizeClass} ${avatarTones[tone]}`}>{initials}</span>; }

export function Badge({ children, tone = "neutral" }: { children: ReactNode; tone?: "success" | "neutral" | "warning" | "danger" }) { const tones = { success: "bg-[#e1f1e7] text-[#2d4f3d]", neutral: "bg-[#f0eeea] text-[#615e57]", warning: "bg-[#f7ecd5] text-[#765629]", danger: "bg-[#fde0dd] text-[#9b2c25]" }; return <span className={`inline-flex items-center gap-1 rounded-full px-2.5 py-1 text-xs font-semibold ${tones[tone]}`}>{children}</span>; }
export function ProgressBar({ value, label }: { value: number; label?: string }) { return <div className="w-full">{label && <div className="mb-2 flex justify-between text-sm text-[#575a55]"><span>{label}</span><span className="font-semibold text-[#163827]">%{value}</span></div>}<div className="h-2 overflow-hidden rounded-full bg-[#e7f0e9]"><div className="h-full rounded-full bg-[#2d4f3d]" style={{ width: `${Math.min(value, 100)}%` }} /></div></div>; }
export function PageHeader({ eyebrow, title, description, action }: { eyebrow?: string; title: string; description?: string; action?: ReactNode }) { return <header className="mb-7 flex flex-col gap-4 sm:mb-9 sm:flex-row sm:items-end sm:justify-between"><div>{eyebrow && <p className="mb-2 text-xs font-bold uppercase tracking-[.12em] text-[#747771]">{eyebrow}</p>}<h1 className="dh-heading text-3xl font-semibold sm:text-[36px]">{title}</h1>{description && <p className="mt-1 text-base text-[#5f625d]">{description}</p>}</div>{action}</header>; }
export function SectionTitle({ title, href, children }: { title: string; href?: string; children?: ReactNode }) { return <div className="mb-5 flex items-center justify-between gap-4"><h2 className="dh-heading text-2xl font-semibold">{title}</h2>{children ?? (href && <a className="dh-focus inline-flex items-center gap-1 text-sm font-semibold text-[#163827]" href={href}>Tümünü Gör <ArrowRight size={16} /></a>)}</div>; }
export function EmptyState({ title, description, action, icon }: { title: string; description: string; action?: ReactNode; icon?: ReactNode }) { return <div className="flex min-h-56 flex-col items-center justify-center rounded-3xl border-2 border-dashed border-[#c5cec5] px-6 text-center"><span className="mb-3 rounded-full bg-[#f3f0ea] p-3 text-[#163827]">{icon ?? <Inbox size={24} />}</span><h3 className="dh-heading text-xl font-semibold">{title}</h3><p className="mt-2 max-w-xs text-[#676a65]">{description}</p>{action && <div className="mt-5">{action}</div>}</div>; }
