/* eslint-disable @next/next/no-img-element */
import Link from "next/link";
import { ArrowLeft, CalendarDays, CheckCircle2, MessageCircle, Utensils } from "lucide-react";
import { clients, recipes } from "@/data/demo";
import { Avatar, Badge, Card, PageHeader, ProgressBar, SectionTitle } from "@/components/ui";
import { ClientActionsMenu } from "@/components/client-actions-menu";

export default async function ClientDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const client = clients.find((item) => item.id === id) ?? clients[0];
  return <><Link href="/diyetisyen/danisanlar" className="dh-focus mb-5 inline-flex items-center gap-2 text-sm font-semibold text-[#2d4f3d]"><ArrowLeft size={17} />Danışanlara dön</Link><PageHeader title={client.name} description={`${client.program} · ${client.camp}`} action={<div className="flex gap-2"><Link href="/diyetisyen/mesajlar" className="dh-focus inline-flex items-center gap-2 rounded-xl bg-[#2d4f3d] px-4 py-3 text-sm font-semibold text-white"><MessageCircle size={18} />Mesaj Gönder</Link><ClientActionsMenu clientName={client.name} /></div>} />
    <div className="grid gap-7 xl:grid-cols-[minmax(0,1.5fr)_360px]"><div className="space-y-7"><Card className="p-6 sm:p-8"><div className="flex flex-col gap-6 sm:flex-row sm:items-center"><Avatar initials={client.initials} tone={client.tone} size="lg" /><div className="flex-1"><div className="flex flex-wrap items-center gap-3"><h2 className="dh-heading text-2xl font-bold">Program ilerlemesi</h2><Badge tone="success">● {client.status}</Badge></div><p className="mt-1 text-[#656761]">{client.day} · Son check-in {client.lastCheckin.toLocaleLowerCase("tr")}</p><div className="mt-4"><ProgressBar value={client.progress} /></div></div></div></Card><Card className="p-6 sm:p-8"><SectionTitle title="Aktif Program" /><div className="rounded-2xl bg-[#e8f2ec] p-5"><div className="flex justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.1em] text-[#4b6b58]">21 günlük kamp</p><h3 className="dh-heading mt-2 text-xl font-bold">Dengeli Yaşam Programı</h3><p className="mt-2 text-[#506154]">Bugünün programı tamamlanmaya hazır.</p></div><CalendarDays className="text-[#2d4f3d]" /></div><Link className="dh-focus mt-5 inline-flex rounded-xl bg-white px-4 py-2.5 text-sm font-semibold text-[#163827]" href="/diyetisyen/kamplar/dengeli-yasam/gunler/15">Günü düzenle</Link></div></Card><Card className="p-6 sm:p-8"><SectionTitle title="Önerilen Tarifler" href="/diyetisyen/tarifler" /><div className="grid gap-3 sm:grid-cols-2">{recipes.slice(0, 2).map((recipe) => <Link href={`/diyetisyen/tarifler`} key={recipe.id} className="dh-focus overflow-hidden rounded-2xl border border-[#e6e3dd]"><img className="h-32 w-full object-cover" src={recipe.image} alt="" /><div className="p-4"><p className="font-semibold">{recipe.name}</p><p className="mt-1 text-sm text-[#686b65]">{recipe.category} · {recipe.duration}</p></div></Link>)}</div></Card></div>
      <div className="space-y-7"><Card className="p-6"><SectionTitle title="Son Check-in" /><p className="text-sm text-[#666963]">Bugün, 09:45</p><h3 className="mt-3 text-lg font-semibold">Kendimi enerjik hissediyorum.</h3><p className="mt-2 text-[#666963]">Su hedefimi tamamladım ve programıma büyük ölçüde uyabildim.</p><Link href="/diyetisyen/checkinler/ayse-yilmaz" className="dh-focus mt-5 inline-flex text-sm font-semibold text-[#2d4f3d]">Check-in detayını gör →</Link></Card><Card className="p-6"><SectionTitle title="Son Aktiviteler" /><div className="space-y-4">{[[CheckCircle2,"Günlük programını tamamladı."],[Utensils,"Öğün fotoğrafı paylaştı."],[MessageCircle,"Diyetisyenine mesaj yazdı."]].map(([Icon, text], index) => { const ActivityIcon = Icon as typeof CheckCircle2; return <div className="flex gap-3" key={String(text)}><ActivityIcon className="mt-0.5 text-[#2d4f3d]" size={19} /><div><p className="text-sm font-medium">{String(text)}</p><p className="text-xs text-[#777a73]">{index === 0 ? "10 dk önce" : `${index + 1} saat önce`}</p></div></div>; })}</div></Card></div></div></>;
}
